### PR TITLE
[JAMES-3226] Automatically publish staging doc

### PR DESCRIPTION
**Pull request by chibenwa**
Trusted version of #3

### CODE REVIEW

**Comment by chibenwa** [comment]
```
Connecting to https://api.github.com to check permissions of obtain list of chibenwa for apache/james-site
Obtained Jenkinsfile from e9da1975d07ca1849c6b4e45302c957aa3fd43ad+cfe1da90052761ac73582d329286ca2febf28c68 (c661365bf415906054084c8c98a702f0594e9909)
Running in Durability level: PERFORMANCE_OPTIMIZED

GitHub has been notified of this commit’s build result

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 93: Expected a step @ line 93, column 13.
               if (env.BRANCH_NAME == "live" ||env.BRANCH_NAME == "staging") {            
               ^

WorkflowScript: 131: Expected a step @ line 131, column 13.
               if (env.BRANCH_NAME == "live" ||env.BRANCH_NAME == "staging") {                            
               ^

2 errors

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:142)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:571)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:523)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:337)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
```

CC Jeantil

**Comment by jeantil** [comment]
thanks @chibenwa 

do you mind changing the job configuration to build PRs from untrusted sources for the moment ? this way I can debug my jenkins jobs before bothering you ...

**Comment by jeantil** [comment]
I pushed 7f7a77b95 at https://github.com/jeantil/james-site/tree/automatically-publish-staging-documenttion-on-james-project-build which should fix it 
not sure if I should reopen a PR or let you fetch from my fork and push here

**Comment by chibenwa** [comment]
I missed that you were targetting staging, not live.

I will close this PR and open a new one.

**Comment by chibenwa** [comment]
See https://github.com/apache/james-site/pull/11

**Pull request closed without merging**
