### PR TITLE
Upgrade packages

### PR DESCRIPTION
**Pull request by Arsnael**

### CODE REVIEW

**Comment by Arsnael** [comment]
Ok trickier than I thought...

**Comment by chibenwa** [comment]
Shouldn't we rather update Antora versions in James Project?

**Comment by Arsnael** [comment]
> Shouldn't we rather update Antora versions in James Project?

We can. It's good to update it on our side as well, but it will not change for the website though, as it takes the antora version declared here I believe to build and deploy.

I forgot to mention last friday but this is what happened pretty much:
- first did those updates and also updated node version to latest (19.xx.yy) and it was compiling fine on my local
- Then on the CI, well version of node was missing. So I took out the node version upgrade commit
- but then build fails. I confirm it fails locally too. I think it is more related to node version

I need to check if we have upper versions of node available on the CI and if yes, which ones, if it's enough to get latest version of antora or not :)

**Review by chibenwa — APPROVED** [review]

**Comment by vttranlina** [comment]
I tried with node 16.14.0 and `com.github.node-gradle.node' version "3.5.1"`, it work
I created a pr at: https://github.com/apache/james-site/pull/37
Build success on my local, 
wait to ci result

**Comment by Arsnael** [comment]
I'm closing this one then, as I think your PR retakes this work and finish the job. Thanks again :)

**Pull request closed without merging**
